# Generated by Django 5.0.4 on 2024-04-23 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0008_auto_20210519_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='give_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 17, 44, 57, 889585)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='take_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 17, 44, 57, 889585)),
        ),
    ]
