# Generated by Django 5.0.4 on 2024-04-24 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0012_alter_orders_give_time_alter_orders_take_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='give_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 23, 59, 24, 642204)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='take_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 23, 59, 24, 642204)),
        ),
    ]
